# Generated by Django 5.0.14 on 2026-06-16 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=100)),
                ('texto_comentario', models.TextField()),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('hora_publicacion', models.TimeField(auto_now_add=True)),
                ('editado', models.BooleanField(default=False)),
                ('archivo_adjunto_url', models.URLField(blank=True, null=True)),
                ('tipo_archivo', models.CharField(blank=True, max_length=50, null=True)),
                ('visibilidad_cliente', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
