# Generated by Django 5.0.14 on 2026-06-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comentario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='archivo_adjunto_url',
        ),
        migrations.AddField(
            model_name='comentario',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='comentarios/'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tarea',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tipo_archivo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
